### PR TITLE
Cache symbolic link flag of local SVN resource as session property

### PR DESCRIPTION
**Pull request by ptziegler**
Calculating the decoration is very slow on Windows, because the SVN client checks several times, whether a resource is a symbolic link. With this change, this check is now calculated only once and then stored as a session property, to be reused for all successive calls.

Resolves https://github.com/subclipse/subclipse/issues/173

### CODE REVIEW

**Comment by ptziegler** [comment]
The general assumption is that the properties of a file generally stay the same. If a file is symbolically linked now, it is very likely to also be symbolically linked in e.g. an hour. Especially for folders, this problem becomes very noticable, as every file checks whether its parent (which is the same folder) is symbolically linked, leading to a lot of excessive checks.

**Comment by markphip** [comment]
Change makes sense. Note that Subclipse really is not maintained any more and I do not have any plans to publish a new release. However once this is merged a new dev build will be posted so you ought to be able to install that version.

**Comment by ptziegler** [comment]
> Note that Subclipse really is not maintained any more and I do not have any plans to publish a new release. However once this is merged a new dev build will be posted so you ought to be able to install that version.

That's perfectly fine. Thanks for the quick response!

**Comment by AlBundy33** [comment]
@markphip where can we download the snapshot?

**Comment by markphip** [comment]
https://github.com/subclipse/subclipse/wiki#snapshot-builds

**Comment by AlBundy33** [comment]
You can use the update-site for snapshot builds

**Comment by movedoa** [comment]
Sure, but having a fixed stable version "pinned" would be nice.
I'm running the current snapshot since a few days without any issues btw. and thx for the fix

**Pull request merged**
