### PR TITLE
Ignore files in symlinked directories

### PR DESCRIPTION
**Pull request by dermojo**
Fixes issue #119 by ignoring all files if their parent is a symbolic link.

### CODE REVIEW

**Comment by markphip** [comment]
The change itself looks simple. Do not have my brain turned on at the moment in a way where I understand if it is correct or not.  As I understand it you want to ignore any resource whose parent is a symlink? Is that what all users would expect?  I do not work with symlinks so do not know the answer.

Also, doesn't this change only check the immediate parent folder?  If say the `src` folder is a symlink and then there are folders and files beneath it. Wouldn't only the top level children be ignored?

**Comment by dermojo** [comment]
You're right, I didn't thing about this recursively, will re-test this.
I think ignoring anything below a symlink (directory) is fine. Assume e.g. a directory layout like this:

    src/
    src/file.txt
    link -> src

If file.txt is changed, it will show up under src/ correctly. It doesn't make sense to show link/file.txt as changed, since link/ isn't *really* the parent of file.txt.
So any child of a symlink actually is the child of some other directory.

**Comment by dermojo** [comment]
Quick update:
I tested with multiple subdirectories below the link / linked directory, and this work as well. But this is unintentional and simply a result from the current isSymLink() implementation, that compares the canonical path against the absolute path, which will trigger if *any* part of the path is a link.

Unfortunately, this also means that if e.g. the project itself already contains a symlink, any changes are now ignored. I'll look into making isSymLink() more correct and add recursive checks.

**Comment by dermojo** [comment]
I updated the symlink handling in commit 9de1231, looks complete to me now.

**Comment by markphip** [comment]
I have some mild concerns that adding this tree walk to every file will slow things down which users already complain about. I am going to merge for now to facilitate testing. Can always roll it back.  Snapshot build will be available at this update site:  https://dl.bintray.com/subclipse/snapshots/subclipse/master-2020/

**Pull request merged**
